### ISSUE TITLE
Header and Toolbar Width does not span the whole page.

### ISSUE THREAD

**Issue by Amdirgol** [Nuirgalad/harav#2]

**Comment by joshlangley** [comment]
This is one of the most common problems of web development.

Every UI element on the page gets a default margin by default, the value of which is determined by the browser. I don't know why this is, but I don't like it.

In this specific case, the `<body>` tag gets it's own margin. To fix this, simply add this to your CSS:
```
body {
  margin: 0;
}
```
Hope that helps!

**Comment by Amdirgol** [comment]
Fixed it, thanks!
