### ISSUE TITLE
404 Stylesheet doesn't work

### ISSUE THREAD

**Issue by Amdirgol** [Nuirgalad/harav#4]

**Comment by joshlangley** [comment]
@Amdirgol just as with the other 404 issue (#3), please provide more clarity as to what you mean.

**Comment by Amdirgol** [comment]
There was something that was in the stylesheet that wasn't registering, but it seems to have fixed itself/

**Comment by Amdirgol** [comment]
There was something that was in the stylesheet that wasn't registering, but it seems to have fixed itself/
